const assert=require('node:assert/strict');
const fs=require('node:fs/promises');
const path=require('node:path');
const os=require('node:os');
module.exports=async function smoke(window,app){
  const root=await fs.mkdtemp(path.join(os.tmpdir(),'stg-desktop-'));
  const output=process.env.STG_SMOKE_OUTPUT||(app.isPackaged?path.join(app.getPath('temp'),'stg-packaged-smoke'):path.join(__dirname,'../tests/artifacts'));await fs.mkdir(output,{recursive:true});
  const evidence=[];const errors=[];
  window.webContents.on('console-message',event=>{if(event.level==='error'||event.level===3)errors.push(event.message);});
  const js=code=>window.webContents.executeJavaScript(code,true);
  const wait=async condition=>{for(let i=0;i<150;i++){if(await js(`document.documentElement.dataset.busy!=='true'&&(${condition})`))return;await new Promise(r=>setTimeout(r,80));}throw new Error('UI wait failed: '+condition);};
  const screenshot=async name=>{
    window.show();window.focus();
    for(let attempt=0;attempt<5;attempt++) {
      await new Promise(r=>setTimeout(r,600));
      try {await fs.writeFile(path.join(output,name),(await window.webContents.capturePage(undefined,{stayAwake:true})).toPNG());return;}
      catch(error){if(attempt===4)throw error;}
    }
  };
  try{
    await fs.cp(app.isPackaged?path.join(process.resourcesPath,'demo/StepsToGreat'):path.join(__dirname,'../demo/StepsToGreat'),root,{recursive:true});
    const visualFixture='# 可视化测试\n\n初始段落。\n\n<!-- s2g-goal-view:start -->\n\n公式 $x^2$ 与 **加粗**。\n\n- [ ] 原始清单\n\n| 列 | 值 |\n| --- | --- |\n| 原文 | 1 |\n\n```python\nprint(21)\n```\n';
    await fs.writeFile(path.join(root,'可视化测试.md'),visualFixture);
    await fs.appendFile(path.join(root,'我的学习/学科/Python/01-认识变量/01_教学引导.md'),'\n[可视化测试](../../../../可视化测试.md)\n');
    await wait("!!document.querySelector('#welcome-import')");
    assert.equal(require('electron').Menu.getApplicationMenu(),null);
    assert.equal(await js("getComputedStyle(document.querySelector('.native-titlebar')).backgroundColor===getComputedStyle(document.querySelector('.workspace-header')).backgroundColor"),true);
    evidence.push('Native menus removed and title bar shares the workspace background');
    await screenshot('theme-mono-welcome.png');
    await screenshot('welcome.png');
    await js(`document.querySelector('#recent').innerHTML='<button id="recent-open">打开测试文件夹</button>';document.querySelector('#recent-open').dataset.root=${JSON.stringify(root)};document.querySelector('#recent-open').click();`);
    await wait("!!document.querySelector('.file.selected')");
    evidence.push('Native IPC folder import and recursive file tree passed');
    await js(`document.querySelector('[data-file="我的学习/学科/Python/01-认识变量/01_教学引导.md"]').click()`);
    await wait("document.querySelectorAll('[data-answer-index]').length===2");
    evidence.push('Guide-to-answer linking and two-question current round passed');
    await js("document.querySelector('[data-answer-tab=records]').click()");
    assert.ok(await js("document.querySelector('#answer-records').textContent.includes('最终复评结果')"));
    assert.ok(await js("document.querySelector('#answer-records').textContent.includes('正确答案与解析')"));
    await js("document.querySelector('[data-answer-tab=document]').click();document.querySelector('#answer-edit-source').click()");
    await js("document.querySelector('#answer-source').value+='\\n面板完整文档编辑验证';document.querySelector('#answer-source').dispatchEvent(new Event('input',{bubbles:true}));document.querySelector('#answer-save-source').click()");
    await wait("document.querySelector('#toast').textContent.includes('回答文档已保存')");
    assert.ok((await fs.readFile(path.join(root,'我的学习/学科/Python/01-认识变量/01_学生回答.md'),'utf8')).includes('面板完整文档编辑验证'));
    await js("document.querySelector('[data-answer-tab=current]').click()");
    evidence.push('Answer workspace exposes complete saved records, tutor sections and in-panel version-checked Markdown editing');
    await js("document.querySelector('#preferences').click()");await wait("!!document.querySelector('#font-size')");
    await js("document.querySelector('#font-size').value='17';document.querySelector('#font-size').dispatchEvent(new Event('input',{bubbles:true}));document.querySelector('#modal-actions button').click()");await wait("document.querySelector('#modal').classList.contains('hidden')");assert.equal(await js("document.documentElement.style.getPropertyValue('--reading-font')"),'17px');
    assert.equal(await js("document.querySelectorAll('.view-toolbar,.format-toolbar,.reader-tools,[data-mode],[data-format],[data-reader-theme],#outline,.reader-progress,#editor-source-toggle').length"),0);evidence.push('Three control rows and their removed feature buttons are absent');
    assert.equal(await js("!!document.querySelector('.sidebar,.scope-tabs,#search')"),false);
    assert.equal(await js("getComputedStyle(document.querySelector('.document-access')).display"),'flex');
    assert.ok(await js("document.querySelector('#tree').textContent.includes('学生回答')"));
    assert.equal(await js("document.querySelectorAll('#tree [data-file]').length"),2);
    assert.equal(await js("document.querySelectorAll('#tree [data-popout]').length"),0);
    assert.equal(await js("document.querySelectorAll('#tree [data-progress]').length"),2);
    await js("document.querySelector('[data-progress=chapter]').click()");await wait("!document.querySelector('#progress-page').classList.contains('hidden')");
    assert.ok(await js("document.querySelector('#chapter-progress').textContent.includes('第一轮')"));
    assert.equal(await js("document.querySelector('#document').classList.contains('hidden')"),true);
    await js("document.querySelector('[data-progress=overall]').click()");await wait("document.querySelector('#progress-title').textContent==='总体进度'");
    assert.ok(await js("document.querySelector('#overall-progress').textContent.includes('0 / 1')"));
    await screenshot('overall-progress.png');
    await js("document.querySelector('#tree [data-file]').click()");await wait("!document.querySelector('#document').classList.contains('hidden')");
    assert.ok(await js("!document.querySelector('#tree').textContent.includes('学习档案')"));
    evidence.push('Four navigation pages: teaching, answer, current chapter progress, overall progress; popout is only inside documents');
    assert.ok(await js("!document.querySelector('#dsh-host').classList.contains('hidden')"));
    await js("document.querySelector('#dsh-input').value='保留会话草稿';document.querySelector('#dsh-input').dispatchEvent(new Event('input',{bubbles:true}));document.querySelector('#dsh-detach').click()");
    await wait("document.querySelector('#dsh-host').classList.contains('hidden')");
    assert.equal((await js('window.stg.dshState()')).draft,'保留会话草稿');
    const floating=require('electron').BrowserWindow.getAllWindows().find(w=>w!==window);
    assert.ok(floating,'DSH opens a separate native window');
    assert.equal(await floating.webContents.executeJavaScript("document.body.classList.contains('dsh-only')"),true);
    assert.equal(await floating.webContents.executeJavaScript("document.querySelector('#dsh-input').value"),'保留会话草稿');
    assert.equal(await floating.webContents.executeJavaScript('typeof require'),'undefined');
    assert.equal(await floating.webContents.executeJavaScript("getComputedStyle(document.querySelector('.workspace-header')).display"),'none');
    await floating.webContents.executeJavaScript('window.stg.dshPin(true)');assert.equal(floating.isAlwaysOnTop(),true);
    await floating.webContents.executeJavaScript("document.querySelector('#dsh-minimize').click()");
    for(let i=0;i<30&&!floating.isMinimized();i++)await new Promise(r=>setTimeout(r,80));
    assert.equal(floating.isMinimized(),true);
    await js('window.stg.dshVisible(true)');assert.equal(floating.isMinimized(),false);
    assert.equal(await floating.webContents.executeJavaScript("document.querySelector('#dsh-input').value"),'保留会话草稿');
    await fs.writeFile(path.join(output,'dsh-native-floating.png'),(await floating.webContents.capturePage(undefined,{stayAwake:true})).toPNG());
    floating.close();await wait("(window.stg.dshState()).then(s=>!s.visible)");
    await js("window.stg.dshMode('docked')");await wait("!document.querySelector('#dsh-host').classList.contains('hidden')");
    assert.equal(await js("document.querySelector('#dsh-input').value"),'保留会话草稿');
    assert.equal(await js("!!document.querySelector('#dsh-host aside,#dsh-host nav')"),false);
    evidence.push('Top document navigation excludes old file sidebars; native DSH dock/float preserves draft');
    await screenshot('theme-mono-lesson.png');
    await screenshot('lesson.png');
    await js(`const inputs=document.querySelectorAll('[data-answer-index]');inputs[0].value='price 是变量名，25 是变量值。';inputs[0].dispatchEvent(new Event('input',{bubbles:true}));inputs[1].value='age = 21\\nprint(age)';inputs[1].dispatchEvent(new Event('input',{bubbles:true}));`);
    await wait("document.querySelector('#draft-status').textContent==='草稿已自动保存'");
    window.webContents.reload();await wait("!!document.querySelector('#welcome-import')");
    await js(`document.querySelector('#recent-open').click()`);await wait("document.querySelectorAll('[data-answer-index]').length===2");
    assert.equal(await js("document.querySelector('[data-answer-index=\"0\"]').value"),'price 是变量名，25 是变量值。');
    assert.ok(!(await fs.readFile(path.join(root,'我的学习/学科/Python/01-认识变量/01_学生回答.md'),'utf8')).includes('price 是变量名'));
    evidence.push('Unsubmitted answer draft recovered after renderer restart without modifying the original document');
    await js("document.querySelector('#submit').click()");
    await wait("document.querySelector('#toast').textContent.includes('作答已追加保存')");
    const answer=path.join(root,'我的学习/学科/Python/01-认识变量/01_学生回答.md');
    const content=await fs.readFile(answer,'utf8');assert.ok(content.includes('price 是变量名'));assert.ok(content.includes('（整课所有轮次通过后由导师填写）'));assert.ok((await fs.readdir(path.join(root,'.stg-desk/backups'))).length>=1);
    evidence.push('UI answer submission persisted original text with backup and retained final placeholders');
    await js("document.querySelector('[data-file=\"我的学习/学科/Python/01-认识变量/01_学生回答.md\"]').click()");await wait("document.querySelector('#editor .tiptap').textContent.includes('price 是变量名')");
    assert.equal(await js("getComputedStyle(document.querySelector('#answers-panel')).display"),'none');
    assert.equal(await js("!!document.querySelector('.mode-tabs')"),false);
    assert.equal(await js("!!document.querySelector('#preview')"),false);
    assert.ok(await js("!!document.querySelector('.content-area.edit .tiptap')"));
    evidence.push('Answer document opens directly in the single editor with no mode tabs, source pane or exercise workspace');
    await screenshot('answer-saved.png');
    await screenshot('editor.png');
    const before=await fs.readFile(answer,'utf8');
    await js("document.querySelector('.tiptap').focus()");
    window.webContents.sendInputEvent({type:'keyDown',keyCode:'End',modifiers:['control']});window.webContents.sendInputEvent({type:'keyUp',keyCode:'End',modifiers:['control']});
    await window.webContents.insertText('\n桌面编辑保存验证');
    await wait("document.querySelector('#save-status').textContent.includes('待保存')");
    window.webContents.sendInputEvent({type:'keyDown',keyCode:'S',modifiers:['control']});window.webContents.sendInputEvent({type:'keyUp',keyCode:'S',modifiers:['control']});await wait("document.querySelector('#save-status').textContent==='已保存'");
    assert.ok((await fs.readFile(answer,'utf8')).includes('桌面编辑保存验证'));assert.ok(before.includes('price 是变量名'));
    evidence.push('Actual WYSIWYG keyboard edit and native UI document save passed');
    await fs.appendFile(answer,'\n外部导师追加');await wait("!document.querySelector('#change-banner').classList.contains('hidden')");
    evidence.push('External document change watcher notified visible UI');
    await js("document.querySelector('.tiptap').focus()");await window.webContents.insertText('\n本地冲突草稿');await wait("document.querySelector('#save-status').textContent.includes('待保存')");
    await js("document.querySelector('#save').click()");await wait("!!document.querySelector('#merge-content')");
    await js("document.querySelector('#merge-content').value+='\\n外部导师追加';document.querySelector('#modal-actions button:last-child').click()");await wait("document.querySelector('#modal').classList.contains('hidden')");assert.ok((await fs.readFile(answer,'utf8')).includes('本地冲突草稿'));assert.ok((await fs.readFile(answer,'utf8')).includes('外部导师追加'));
    evidence.push('Side-by-side conflict comparison and explicit merged save preserved both edits');
    assert.ok(await js("window.stg.backups('我的学习/学科/Python/01-认识变量/01_学生回答.md').then(items=>items.length>0)"));
    evidence.push('Version-checked saves continue making automatic backups without a history control row');
    await js("document.querySelector('#choose-course').click()");await wait("!document.querySelector('#modal').classList.contains('hidden')");await js("document.querySelector('[data-file=\"可视化测试.md\"]').click()");await wait("document.querySelector('#editor .tiptap').textContent.includes('初始段落')");await wait("!!document.querySelector('.tiptap')");assert.equal(await fs.readFile(path.join(root,'可视化测试.md'),'utf8'),visualFixture);assert.equal(await js("document.querySelector('#save-status').textContent"),'已保存');
    await js("document.querySelector('.tiptap').focus()");window.webContents.sendInputEvent({type:'keyDown',keyCode:'End',modifiers:['control']});window.webContents.sendInputEvent({type:'keyUp',keyCode:'End',modifiers:['control']});await window.webContents.insertText('可视化新增内容');await wait("document.querySelector('#save-status').textContent.includes('待保存')");await js("document.querySelector('#save').click()");await wait("document.querySelector('#save-status').textContent==='已保存'");const visualSaved=await fs.readFile(path.join(root,'可视化测试.md'),'utf8');assert.ok(visualSaved.includes('可视化新增内容'));for(const original of ['<!-- s2g-goal-view:start -->','公式 $x^2$ 与 **加粗**。','- [ ] 原始清单','| 原文 | 1 |','print(21)'])assert.ok(visualSaved.includes(original));await screenshot('visual-editor.png');evidence.push('Single-column WYSIWYG typing saved through version-checked IPC');
    await js("document.querySelector('.visual-math').dispatchEvent(new MouseEvent('mousedown',{bubbles:true,button:0}))");assert.ok(await js("!!document.querySelector('.tiptap .visual-math .katex')&&!document.querySelector('.cm-live-active')"));assert.equal(await js("document.querySelector('#save-status').textContent"),'已保存');evidence.push('Clicking a rendered formula preserves visual formatting and saved content');
    await js("document.querySelector('.tiptap').editor.commands.setTextSelection({from:1,to:3});document.querySelector('.tiptap').focus()");window.webContents.sendInputEvent({type:'keyDown',keyCode:'B',modifiers:['control']});window.webContents.sendInputEvent({type:'keyUp',keyCode:'B',modifiers:['control']});await wait("document.querySelector('#save-status').textContent.includes('待保存')");window.webContents.sendInputEvent({type:'keyDown',keyCode:'Z',modifiers:['control']});window.webContents.sendInputEvent({type:'keyUp',keyCode:'Z',modifiers:['control']});await wait("document.querySelector('#save-status').textContent==='已保存'");evidence.push('Native editing shortcuts and undo work without a formatting toolbar');
    await js("document.querySelector('.tiptap').focus()");window.webContents.sendInputEvent({type:'keyDown',keyCode:'A',modifiers:['control']});window.webContents.sendInputEvent({type:'keyUp',keyCode:'A',modifiers:['control']});window.webContents.sendInputEvent({type:'keyDown',keyCode:'Backspace'});window.webContents.sendInputEvent({type:'keyUp',keyCode:'Backspace'});await wait("document.querySelector('#save-status').textContent.includes('待保存')");await js("document.querySelector('#save').click()");await wait("document.querySelector('#save-status').textContent==='已保存'");assert.equal(await fs.readFile(path.join(root,'可视化测试.md'),'utf8'),'');evidence.push('Deleting all content saves an empty document without resurrecting the old text');
    await js("document.querySelector('#continue-learning').click()");await wait("document.querySelectorAll('[data-answer-index]').length===2");await wait("document.querySelector('#toast').classList.contains('hidden')");await screenshot('refined-lesson.png');
    assert.equal(await js('typeof require'),'undefined');assert.equal(await js('typeof process'),'undefined');
    evidence.push('Renderer has no Node require/process access');
    const guidePath='我的学习/学科/Python/01-认识变量/01_教学引导.md',answerPath='我的学习/学科/Python/01-认识变量/01_学生回答.md';
    const findDocument=relative=>require('electron').BrowserWindow.getAllWindows().find(w=>w!==window&&new URL(w.webContents.getURL()||'file:///').searchParams.get('document')===relative);
    await js("document.querySelector('#document-popout').click()");await wait(`document.querySelector('#status-left').textContent===${JSON.stringify(answerPath)}`);
    assert.equal(await js(`document.querySelector('#tree [data-file="${guidePath}"]').disabled`),true);
    await js(`document.querySelector('#tree [data-file="${guidePath}"]').click()`);assert.equal(await js("document.querySelector('#status-left').textContent"),answerPath);
    await js("document.querySelector('[data-progress=overall]').click()");await wait("document.querySelector('#progress-title').textContent==='总体进度'&&!document.querySelector('#progress-page').classList.contains('hidden')");
    await screenshot('detached-progress.png');
    findDocument(guidePath).close();await wait(`document.querySelector('#status-left').textContent===${JSON.stringify(guidePath)}&&!document.querySelector('#document').classList.contains('hidden')`);
    assert.equal(await js(`document.querySelector('#tree [data-file="${guidePath}"]').disabled`),false);
    await js(`document.querySelector('#tree [data-file="${answerPath}"]').click()`);await wait(`document.querySelector('#status-left').textContent===${JSON.stringify(answerPath)}`);
    await js("document.querySelector('#document-popout').click()");await wait(`document.querySelector('#status-left').textContent===${JSON.stringify(guidePath)}`);
    assert.equal(await js(`document.querySelector('#tree [data-file="${answerPath}"]').disabled`),true);
    assert.equal(await js("getComputedStyle(document.querySelector('#answers-panel')).display"),'none');
    const detachedAnswer=findDocument(answerPath);
    for(let i=0;i<100;i++){if(await detachedAnswer.webContents.executeJavaScript("!!document.querySelector('.tiptap')&&document.documentElement.dataset.busy==='false'",true))break;await new Promise(r=>setTimeout(r,80));}
    detachedAnswer.show();detachedAnswer.focus();await new Promise(r=>setTimeout(r,150));
    detachedAnswer.show();detachedAnswer.focus();detachedAnswer.webContents.focus();
    await detachedAnswer.webContents.executeJavaScript("document.querySelector('.tiptap').focus()",true);
    detachedAnswer.webContents.sendInputEvent({type:'keyDown',keyCode:'End',modifiers:['control']});detachedAnswer.webContents.sendInputEvent({type:'keyUp',keyCode:'End',modifiers:['control']});
    await detachedAnswer.webContents.insertText('\n独立窗口草稿交接验证');
    for(let i=0;i<100;i++){if(await detachedAnswer.webContents.executeJavaScript("document.querySelector('#save-status').textContent.includes('待保存')",true))break;await new Promise(r=>setTimeout(r,80));}
    if(!await detachedAnswer.webContents.executeJavaScript("document.querySelector('#save-status').textContent.includes('待保存')",true)){await fs.writeFile(path.join(output,'child-input-failure.png'),(await detachedAnswer.webContents.capturePage()).toPNG());console.log(await detachedAnswer.webContents.executeJavaScript("JSON.stringify({active:document.activeElement?.className,editable:document.querySelector('.tiptap')?.contentEditable,text:document.querySelector('.tiptap')?.textContent,mode:document.querySelector('#content-area')?.className,toast:document.querySelector('#toast')?.textContent})",true));}
    assert.ok(await detachedAnswer.webContents.executeJavaScript("document.querySelector('#save-status').textContent.includes('待保存')",true));
    for(let i=0;i<100;i++){if(await detachedAnswer.webContents.executeJavaScript("document.querySelector('#save-status').textContent.includes('待保存')",true))break;await new Promise(r=>setTimeout(r,80));}
    if(!await detachedAnswer.webContents.executeJavaScript("document.querySelector('#save-status').textContent.includes('待保存')",true)){await fs.writeFile(path.join(output,'child-input-failure.png'),(await detachedAnswer.webContents.capturePage()).toPNG());console.log(await detachedAnswer.webContents.executeJavaScript("JSON.stringify({active:document.activeElement?.className,editable:document.querySelector('.tiptap')?.contentEditable,text:document.querySelector('.tiptap')?.textContent,mode:document.querySelector('#content-area')?.className,toast:document.querySelector('#toast')?.textContent})",true));}
    assert.ok(await detachedAnswer.webContents.executeJavaScript("document.querySelector('#save-status').textContent.includes('待保存')",true));
    detachedAnswer.close();await wait(`document.querySelector('#status-left').textContent===${JSON.stringify(answerPath)}`);
    assert.ok((await js(`window.stg.draftGet(${JSON.stringify(answerPath)})`)).content.includes('独立窗口草稿交接验证'));
    assert.ok(await js("document.querySelector('#save-status').textContent.includes('待保存')"));
    await js("document.querySelector('.tiptap').focus()");window.webContents.sendInputEvent({type:'keyDown',keyCode:'End',modifiers:['control']});window.webContents.sendInputEvent({type:'keyUp',keyCode:'End',modifiers:['control']});
    await wait("document.querySelector('.tiptap').textContent.includes('独立窗口草稿交接验证')");
    assert.ok(!(await fs.readFile(answer,'utf8')).includes('独立窗口草稿交接验证'));
    evidence.push('Closing a detached document hands its unsaved draft back to the main editor without writing the formal document');
    assert.equal(await js(`document.querySelector('#tree [data-file="${answerPath}"]').disabled`),false);
    evidence.push('Popping either document switches the main app to its counterpart, disables the detached tab, keeps progress pages accessible, and closing restores the document');
    await js("document.querySelector('#document-popout').click()");await wait(`document.querySelector('#status-left').textContent===${JSON.stringify(guidePath)}`);
    await js("document.querySelector('#document-popout').click()");await wait("!document.querySelector('#progress-page').classList.contains('hidden')");
    let student,teacher;
    for(let i=0;i<100;i++){const all=require('electron').BrowserWindow.getAllWindows();student=all.find(w=>w!==window&&new URL(w.webContents.getURL()||'file:///').searchParams.get('document')===answerPath);teacher=all.find(w=>w!==window&&new URL(w.webContents.getURL()||'file:///').searchParams.get('document')===guidePath);if(student&&teacher)break;await new Promise(r=>setTimeout(r,80));}
    assert.ok(student&&teacher,'Both documents open in their own native windows');
    const childJS=code=>student.webContents.executeJavaScript(code,true);
    for(let i=0;i<100;i++){if(await childJS("document.body.classList.contains('answer-document-window')&&document.querySelector('.content-area.edit')&&document.documentElement.dataset.busy==='false'"))break;await new Promise(r=>setTimeout(r,80));}
    assert.equal(await childJS("getComputedStyle(document.querySelector('.workspace-header')).display"),'none');
    assert.equal(await childJS("getComputedStyle(document.querySelector('#content-area')).display"),'flex');
    assert.equal(await childJS("getComputedStyle(document.querySelector('#answers-panel')).display"),'none');
    assert.equal(await childJS("!!document.querySelector('.mode-tabs')"),false);
    assert.equal(await childJS("!!document.querySelector('#preview')"),false);
    assert.equal(await childJS('typeof require'),'undefined');
    assert.equal(await childJS("document.querySelector('#status-left').textContent"),answerPath);
    await childJS(`window.stg.documentWindowOpen(${JSON.stringify(answerPath)})`);assert.equal(require('electron').BrowserWindow.getAllWindows().filter(w=>new URL(w.webContents.getURL()||'file:///').searchParams.get('document')===answerPath).length,1);
    const otherRoot=await fs.mkdtemp(path.join(os.tmpdir(),'stg-window-other-'));await fs.cp(app.isPackaged?path.join(process.resourcesPath,'demo/StepsToGreat'):path.join(__dirname,'../demo/StepsToGreat'),otherRoot,{recursive:true});
    await js(`document.querySelector('#recent').innerHTML='<button id="recent-open">切换测试工作区</button>';document.querySelector('#recent-open').dataset.root=${JSON.stringify(otherRoot)};document.querySelector('#recent-open').click()`);await wait(`document.querySelector('#status-left').textContent.includes('教学引导.md')`);
    assert.equal((await childJS('window.stg.documentWindowInfo()')).root,await fs.realpath(root));
    window.destroy();
    student.show();student.focus();student.webContents.focus();
    await childJS("document.querySelector('.tiptap').focus()");
    student.webContents.sendInputEvent({type:'keyDown',keyCode:'End',modifiers:['control']});student.webContents.sendInputEvent({type:'keyUp',keyCode:'End',modifiers:['control']});
    await student.webContents.insertText('\n主窗口关闭后仍能独立答题');
    await childJS("document.querySelector('#save').click()");
    for(let i=0;i<100;i++){if(await childJS("document.querySelector('#save-status').textContent==='已保存'"))break;await new Promise(r=>setTimeout(r,80));}
    assert.ok((await fs.readFile(answer,'utf8')).includes('主窗口关闭后仍能独立答题'));
    assert.equal(await childJS("document.querySelector('#status-left').textContent"),answerPath);
    assert.ok(!(await fs.readFile(path.join(otherRoot,answerPath),'utf8')).includes('主窗口关闭后仍能独立答题'));
    await new Promise(r=>setTimeout(r,300));await fs.writeFile(path.join(output,'student-window.png'),(await student.webContents.capturePage(undefined,{stayAwake:true})).toPNG());await fs.writeFile(path.join(output,'teaching-window.png'),(await teacher.webContents.capturePage(undefined,{stayAwake:true})).toPNG());
    evidence.push('Two independent document windows reuse identity, remain sandboxed, keep their original workspace after main switches and save answers after main closes');
    assert.deepEqual(errors,[]);
    await fs.writeFile(path.join(output,'desktop-smoke.json'),JSON.stringify({passed:true,evidence,rendererErrors:errors},null,2));
    console.log(JSON.stringify({passed:true,evidence,artifacts:output},null,2));
    app.exit(0);
  }catch(error){await screenshot('failure.png').catch(()=>{});await fs.writeFile(path.join(output,'desktop-smoke.json'),JSON.stringify({passed:false,evidence,error:error.stack,toast:await js("document.querySelector('#toast')?.textContent"),rendererErrors:errors},null,2));console.error(error);app.exit(1);}
  finally{await fs.rm(root,{recursive:true,force:true}).catch(()=>{});}
};

